spring:

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/kupuvalnik?useSSL=false&createDatabaseIfNotExist=true&serverTimezone=UTC"
    username: root
    password: ${dbPassword}
    #cloudinary file size
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  sql:
    init:
      mode: always
  jpa:
    # Choose either MySQL 8 or MySQL 5 below
    # For MySQL 8
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    #For MySQL 5
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  mvc:
    hiddenmethod:
      filter:
        enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
cloudinary:
  api-key: 433443414642629
  api-secret: ${cloudinary_api_secret}
  cloud-name: kupuvalnik-cloud

server:
  error:
    include-stacktrace: never




